### ISSUE TITLE
Language list page title does not update to newly selected list

### ISSUE THREAD

**Issue by PaulHeggarty** [lingdb/CoBL#124]
http://www.cobl.info/languagelist/2016-04-04_Export/
is still showing with the page title [Language list ‘all’]
When fixing this, please also show the title in the following format (i.e. with a colon and without ' ' marks):
Language list:  all
Language list:  2016-04-04_Export
etc..

(This header should also remain visible when scrolling down, as per another issue.)

**Comment by runjak** [comment]
I have problems reproducing the problem.
![screenshot_2016-04-08_12-42-30](https://cloud.githubusercontent.com/assets/5417642/14381568/8c2324ce-fd87-11e5-9752-c6b16efa60d1.png)
![screenshot_2016-04-08_12-42-54](https://cloud.githubusercontent.com/assets/5417642/14381569/8c243512-fd87-11e5-8e93-9041c23d691d.png)
When I select a language list the correct list shows up both on the page and in the page title correctly. I've just rolled out an update so it may be that this problem was fixed as a side effect of that.
I'll make sure to adjust the format of the page title and close this issue afterwards.

**Comment by PaulHeggarty** [comment]
This is my screenshot.  List is correctly set in the table, but the header remains stuck on all.
![screenshot - 08_04_2016 13_13_13](https://cloud.githubusercontent.com/assets/8819910/14382115/b9391a50-fd8b-11e5-9e47-36998b301682.png)
It may be a cache problem, because it is not a problem for Moreno or for Cormac, or you, or on my laptop in a different browser.  But worth knowing about.  I'll clear my cache and try again.

**Comment by PaulHeggarty** [comment]
I cleared my cache but it did not fix the problem, so that's not it.
But then I logged out and back in again, and it did fix it.  Perhaps that will help you diagnose, and decide whether you can just drop this issue or it needs to be investigated because it might recur.  I think it may just be that it was so long since I logged in that an update in the meantime caused this bug and it probably won't come back now.  If you agree, feel free to close the issue.

**Comment by runjak** [comment]
OK - interesting situation.
This issue will be closed automagically once I deploy an update to the server that fixes the format. It's good to have this noted though in case that something like this creeps up again.
